/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/corridorOptimized.glb --transform 
Files: public/models/corridorOptimized.glb [882.68KB] > corridorOptimized-transformed.glb [132.5KB] (85%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/corridorOptimized-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ATomarColor">
          <mesh name="Cube1003" geometry={nodes.Cube1003.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_1" geometry={nodes.Cube1003_1.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_2" geometry={nodes.Cube1003_2.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_3" geometry={nodes.Cube1003_3.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_4" geometry={nodes.Cube1003_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_5" geometry={nodes.Cube1003_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_6" geometry={nodes.Cube1003_6.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_7" geometry={nodes.Cube1003_7.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_8" geometry={nodes.Cube1003_8.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_9" geometry={nodes.Cube1003_9.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_10" geometry={nodes.Cube1003_10.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_11" geometry={nodes.Cube1003_11.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_12" geometry={nodes.Cube1003_12.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_13" geometry={nodes.Cube1003_13.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_14" geometry={nodes.Cube1003_14.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_15" geometry={nodes.Cube1003_15.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_16" geometry={nodes.Cube1003_16.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_17" geometry={nodes.Cube1003_17.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_18" geometry={nodes.Cube1003_18.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_19" geometry={nodes.Cube1003_19.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_20" geometry={nodes.Cube1003_20.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_21" geometry={nodes.Cube1003_21.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_22" geometry={nodes.Cube1003_22.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_23" geometry={nodes.Cube1003_23.geometry} material={materials['Palette.003']} />
          <mesh name="Cube1003_24" geometry={nodes.Cube1003_24.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_25" geometry={nodes.Cube1003_25.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_26" geometry={nodes.Cube1003_26.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_27" geometry={nodes.Cube1003_27.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_28" geometry={nodes.Cube1003_28.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_29" geometry={nodes.Cube1003_29.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_30" geometry={nodes.Cube1003_30.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_31" geometry={nodes.Cube1003_31.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_32" geometry={nodes.Cube1003_32.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_33" geometry={nodes.Cube1003_33.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_34" geometry={nodes.Cube1003_34.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_35" geometry={nodes.Cube1003_35.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_36" geometry={nodes.Cube1003_36.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_37" geometry={nodes.Cube1003_37.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_38" geometry={nodes.Cube1003_38.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_39" geometry={nodes.Cube1003_39.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_40" geometry={nodes.Cube1003_40.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_41" geometry={nodes.Cube1003_41.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_42" geometry={nodes.Cube1003_42.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_43" geometry={nodes.Cube1003_43.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Cube1003_44" geometry={nodes.Cube1003_44.geometry} material={materials.PaletteMaterial002} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/corridorOptimized-transformed.glb')
